app:
    nexus-iq:
        url: TO_BE_PROVIDED        # everything until "api/v2". Should end with a "/" character
        username: TO_BE_PROVIDED   # the username or the token's user code. See the README
        password: TO_BE_PROVIDED   # the password or the token's passcode

spring:
    main:
        web-application-type: NONE
