# This workflow builds the project with Maven and performs its Sonar (SonarCloud) analysis.

name: CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-sonar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'
      - name: Build and Sonar
        run: mvn -B -U verify sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=etat-de-geneve-github -Dsonar.projectKey=republique-et-canton-de-geneve_nexus-iq-dashboard-extractor
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
